In [1]:
import numpy as np

In [2]:
two_D_Array = np.array(np.arange(16).reshape(4,4))
print(two_D_Array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [3]:
three_D_Array = np.array(two_D_Array.reshape(4,2,2))
print(three_D_Array)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]]


In [4]:
new_3_D_Array = (three_D_Array + 5 - 2 ) * 5
print(new_3_D_Array)

[[[15 20]
  [25 30]]

 [[35 40]
  [45 50]]

 [[55 60]
  [65 70]]

 [[75 80]
  [85 90]]]
